In [8]:
!unzip ./converted_keras.zip

Archive:  ./converted_keras.zip
replace keras_model.h5? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace labels.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [9]:
!pip install Discord
# importamos la libreria PIL: Python Imaging Library
# es necesario para poder abrir la imagen a analizar
import PIL
from PIL import Image, ImageOps
import numpy as np
# Instalamos keras, libreria necesaria para que funcionen
# las redes neuronales
!pip install -q tf-keras==2.19.0 h5py==3.11.0
# Importando tf-keras – una versión de Keras compatible con modelos .h5
import tf_keras as keras
# Importando la función load_model de tf_keras, que nos
# permitira cargar el modelo de google teachable machine
from tf_keras.models import load_model

/usr/lib/python3.13/pathlib/_local.py:277: RuntimeWarning: coroutine 'Client.run.<locals>.runner' was never awaited
  @property


  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement tensorflow<2.20,>=2.19 (from tf-keras) (from versions: 2.20.0rc0, 2.20.0, 2.21.0rc0, 2.21.0rc1, 2.21.0, 2.22.0rc0)
ERROR: No matching distribution found for tensorflow<2.20,>=2.19


In [10]:
model_path = "/content/keras_model.h5"
labels_path = "/content/labels.txt"

def inference(image_path):
  np.set_printoptions(suppress=True)
  model = load_model(model_path, compile=False)
  class_names = open(labels_path, "r").readlines()
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
  image = Image.open(image_path).convert("RGB")
  size = (224, 224)
  image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
  image_array = np.asarray(image)
  normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1
  data[0] = normalized_image_array
  prediction = model.predict(data)
  print(prediction)
  index = np.argmax(prediction)
  class_name = class_names[index]
  confidence_score = prediction[0][index]
  text1 = f"Class: {class_name[2:]} Confidence Score: {confidence_score}"
  return text1

In [11]:
import nest_asyncio
nest_asyncio.apply()

In [ ]:
import discord
from discord.ext import commands
#Definimos los permisos del bot
intents = discord.Intents.default()
intents.message_content = True
#creamos el bot
bot = commands.Bot(command_prefix='$', intents=intents)

@bot.event
async def on_ready():
    print(f'We have logged in as {bot.user}')


#este comando saluda al usuario
#para activarlo se escribe   $hello
@bot.command()
async def hello(ctx):
    await ctx.send(f'Hi! I am a bot {bot.user}!')

#escribe tu codigo aqui
@bot.command()
async def check(ctx):
  if ctx.message.attachments:
    for attachment in ctx.message.attachments:
      file_name = attachment.filename
      await attachment.save(f"./{file_name}")
      await ctx.send("La imagen fue guardada con exito")
      await ctx.send(inference(f"./{file_name}"))
  else:
    await ctx.send("No se encontro ninguna imagen")


bot.run("MTQ2MzMwNDIzNzM3NDI0Mjk0Mg.G_tDRA.JaxchDrwJpP-nj0MRStMIxOmHeOSY8bI23Ej7A")

2026-09-27 21:46:15 INFO     discord.client logging in using static token
2026-09-27 21:46:15 INFO     discord.client logging in using static token
2026-09-27 21:46:15 INFO     discord.client logging in using static token
INFO:discord.client:logging in using static token
2026-09-27 21:46:16 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 78e86d999285fbedb192295a2dde1244).
2026-09-27 21:46:16 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 78e86d999285fbedb192295a2dde1244).
2026-09-27 21:46:16 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 78e86d999285fbedb192295a2dde1244).
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 78e86d999285fbedb192295a2dde1244).


We have logged in as python.pro#8590
1/1 [==============================] - 1s 1s/step
[[0.00039776 0.00002959 0.00020306 0.00000478 0.9993648 ]]
1/1 [==============================] - 1s 1s/step
[[0.07079321 0.00227388 0.28551787 0.63381207 0.00760301]]
1/1 [==============================] - 1s 913ms/step
[[0.11549577 0.05213262 0.76178104 0.04851522 0.02207533]]
1/1 [==============================] - 1s 1s/step
[[0.14291748 0.83292645 0.00164983 0.02180498 0.00070128]]


1/1 [==============================] - 1s 863ms/step
[[0.5805208  0.38160172 0.02728541 0.00436678 0.00622525]]


1/1 [==============================] - 1s 865ms/step
[[0.9997869  0.00001676 0.00005541 0.00002577 0.00011512]]
1/1 [==============================] - 1s 895ms/step
[[0.00420073 0.00033846 0.00136877 0.00020113 0.9938909 ]]
